
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 112
#define YY_END_OF_BUFFER 113
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[387] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,  113,  111,
       96,   96,   64,   97,   95,   57,  111,   65,   66,   55,
       58,   61,   59,  111,   56,   94,   94,   71,   62,   60,
       63,   95,   95,   69,   70,   54,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   67,  111,   68,  108,  107,  107,  108,  104,
      103,  112,  105,  112,  110,  109,  109,   48,   95,   45,
        1,    2,   51,   92,    0,   88,   89,   91,    0,   94,
        0,   52,   50,   47,   49,   53,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   13,

       95,   95,   95,   95,   95,   95,   95,   95,   78,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   46,  107,
      106,  104,  102,   99,  101,   98,  109,   92,    0,    0,
        0,   90,    0,    0,   93,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   43,   95,   95,   95,
       79,   95,   95,   44,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       31,   95,   95,   95,  100,    0,   92,    0,   90,    0,

        0,    0,   91,   93,    0,   95,   95,   95,   95,   95,
       95,   95,   21,   24,   95,   32,   95,   95,   95,   95,
       95,   77,   25,   95,   95,   95,   95,   14,   95,   95,
       95,   95,   36,   95,    3,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   16,   95,   95,   72,
       86,   95,   95,   92,    0,    0,    0,   90,   91,    0,
       95,   95,   95,   95,   95,   95,   17,   28,   74,   39,
       95,   95,   95,   95,   33,   40,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   30,   95,   95,   42,
       95,   95,   20,   95,   95,   87,    0,   90,    0,   95,

       85,    5,   95,    9,   95,   95,   95,   76,   95,   95,
       95,   22,   95,   95,   41,   95,   95,   95,   82,   83,
       84,   95,    8,   95,   23,   95,   95,   75,    4,    0,
       95,   73,   95,   10,   29,   35,   95,   95,   95,   11,
       15,   95,   95,   95,   95,   95,    0,    0,    6,    7,
       95,   95,   95,   95,   37,   95,   95,   38,    0,    0,
       95,   95,   34,   19,   95,   27,    0,    0,   18,   26,
       95,    0,    0,   95,    0,    0,   12,    0,    0,    0,
        0,    0,    0,   81,   80,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    7,    8,    9,    1,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,    1,   20,   21,
       22,   23,    1,    1,    7,    7,    7,    7,   24,    7,
        7,    7,   25,    7,    7,    7,    7,    7,    7,    7,
        7,    7,   26,    7,    7,    7,    7,    7,    7,    7,
       27,   28,   29,   30,   31,    1,   32,   33,   34,   35,

       36,   37,   38,   39,   40,    7,   41,   42,   43,   44,
       45,   46,    7,   47,   48,   49,   50,   51,   52,   53,
       54,   55,   56,   57,   58,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[59] =
    {   0,
        1,    1,    2,    2,    1,    2,    3,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    3,    1,
        1,    1,    1,    3,    3,    3,    1,    2,    1,    1,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    1,    1,    1
    } ;

static const flex_int16_t yy_base[393] =
    {   0,
        0,    0,   56,   58,   60,   68,   72,   74,  494,  495,
      495,  495,  471,  495,    0,  495,  483,  495,  495,  495,
      478,  495,   50,   61,   69,   66,   73,  495,   62,  468,
       71,  445,   46,  495,  495,  495,   65,   54,   73,   71,
       75,   82,  443,   86,  442,   89,   88,  450,   92,   87,
      440,  445,  495,  426,  495,  495,  495,  479,  464,    0,
      495,  495,  495,  144,  495,  495,  477,  495,    0,  495,
      495,  495,  495,  133,  443,  495,  495,  135,  143,  149,
      114,  495,  495,  495,  495,  495,  429,  430,  428,  427,
      426,  428,  436,  422,   62,  438,  437,  424,  430,  416,

      417,  414,  414,  420,  417,  415,  412,  409,    0,  411,
       88,  412,  406,  402,  411,  418,  115,  418,  401,  404,
      131,  402,  407,  402,  130,  142,   27,  405,  495,  495,
      495,    0,  495,  495,  441,  495,  495,  171,  185,  168,
      399,  187,  195,  157,  197,  406,  401,  391,  390,  402,
      395,  404,  399,  398,  399,  385,  383,  134,  398,  396,
      392,  384,  390,  377,  392,  391,    0,  377,   98,  372,
      384,  381,  378,    0,  375,  375,  364,  365,  371,  362,
      364,  361,  369,  372,  358,  372,  357,  359,  359,  366,
        0,  366,  368,  357,  495,  201,  203,  360,  206,  214,

      217,  220,  222,  225,  227,  359,  352,  359,  347,  346,
      356,  350,    0,    0,  351,    0,  341,  339,  347,  336,
      343,    0,    0,  340,  347,  340,  332,    0,  344,  332,
      346,  330,    0,  325,    0,  343,  342,  337,  332,  324,
      321,  329,  334,  320,  332,  326,    0,  312,  315,    0,
        0,  313,  325,  231,  233,  311,  236,  241,  247,  249,
      323,  320,  314,  324,  306,  322,    0,    0,    0,    0,
      309,  310,  315,  315,  307,    0,  305,  298,  302,  308,
      308,  305,  293,  307,  306,  295,    0,  304,  288,    0,
      297,  288,  286,  293,  292,    0,  292,  251,  255,  283,

        0,  313,  294,    0,  283,  276,  276,    0,  276,  269,
      286,    0,  287,  288,    0,  283,  282,  268,    0,    0,
        0,  279,    0,  270,    0,  278,  271,  495,  296,  266,
      261,    0,  273,    0,    0,    0,  264,  271,  272,    0,
        0,  269,  258,  259,  258,  261,  239,  234,    0,    0,
      234,  236,  243,  242,    0,  236,  226,    0,  239,  214,
      213,  220,    0,    0,  192,    0,  184,  210,    0,    0,
      181,  164,  163,  166,  161,  147,    0,  159,  139,  122,
      105,   57,   38,  495,  495,  495,  286,  289,  292,   82,
      295,  298

    } ;

static const flex_int16_t yy_def[393] =
    {   0,
      386,    1,  387,  387,  388,  388,  389,  389,  386,  386,
      386,  386,  386,  386,  390,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  390,  390,  386,  386,  386,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  386,  386,  386,  386,  386,  386,  386,  391,
      386,  386,  386,  392,  386,  386,  386,  386,  390,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,

      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  386,  386,
      386,  391,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  386,  386,  386,  386,  386,  386,

      386,  386,  386,  386,  386,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  386,  386,  386,  386,  386,  386,  386,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  386,  386,  386,  390,

      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  386,  390,  386,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  386,  386,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  386,  386,
      390,  390,  390,  390,  390,  390,  386,  386,  390,  390,
      390,  386,  386,  390,  386,  386,  390,  386,  386,  386,
      386,  386,  386,  386,  386,    0,  386,  386,  386,  386,
      386,  386

    } ;

static const flex_int16_t yy_nxt[554] =
    {   0,
       10,   11,   12,   11,   13,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   15,   32,   33,   34,   10,   35,   36,
       15,   37,   38,   39,   40,   41,   42,   43,   15,   44,
       15,   45,   15,   46,   15,   47,   48,   49,   50,   15,
       51,   52,   15,   15,   15,   53,   54,   55,   57,   58,
       57,   58,   61,   62,   72,   63,  192,   59,  193,   59,
       61,   62,   73,   63,   66,   67,   66,   67,   74,   74,
       76,   78,   82,   83,   69,   77,  385,   64,   78,   79,
       80,   80,   85,   86,   88,   64,   79,   90,   92,   89,

       93,   79,   75,   81,   95,  384,   99,   94,   79,  154,
      155,   96,   91,  104,   97,  100,  101,   98,  102,  116,
      113,  105,  109,  106,  114,  125,  107,  103,  110,  111,
      120,   80,   80,  126,  117,  170,  171,  118,  115,  229,
      121,  122,  230,  123,   81,  124,  134,  135,  383,  136,
      138,  138,  142,  142,  177,  144,  139,  144,  143,  178,
      145,  145,  182,  140,   78,  382,   80,   80,  139,  187,
      143,  136,   79,  189,  145,  145,  188,  183,  381,   81,
      136,  218,  219,  380,   79,  138,  138,  136,  138,  138,
      136,  190,  136,  379,  139,  191,  378,  196,  140,  196,

      377,  140,  197,  197,  199,  199,  139,  202,  376,  202,
      200,  375,  203,  203,  204,  204,  374,  201,  197,  197,
      254,  254,  200,  199,  199,  373,  257,  205,  257,  200,
      372,  258,  258,  255,  199,  199,  201,  203,  203,  259,
      259,  200,  204,  204,  204,  204,  371,  201,  254,  254,
      254,  254,  260,  258,  258,  205,  370,  205,  298,  298,
      369,  255,  368,  255,  259,  259,  259,  259,  298,  298,
      367,  299,  298,  298,  366,  365,  364,  260,  363,  260,
      362,  299,  361,  360,  359,  299,   56,   56,   56,   60,
       60,   60,   65,   65,   65,  132,  358,  132,  133,  133,

      133,  357,  356,  355,  354,  353,  352,  351,  350,  349,
      348,  347,  346,  345,  344,  343,  342,  341,  340,  339,
      338,  337,  336,  335,  334,  333,  332,  331,  330,  329,
      328,  327,  326,  325,  324,  323,  322,  321,  320,  319,
      318,  317,  316,  315,  314,  313,  312,  311,  310,  309,
      308,  307,  306,  305,  304,  303,  302,  301,  300,  297,
      296,  295,  294,  293,  292,  291,  290,  289,  288,  287,
      286,  285,  284,  283,  282,  281,  280,  279,  278,  277,
      276,  275,  250,  274,  273,  272,  271,  270,  269,  268,
      267,  266,  265,  264,  263,  262,  261,  256,  253,  252,

      251,  250,  249,  248,  247,  246,  245,  244,  243,  242,
      241,  240,  239,  238,  237,  236,  235,  234,  233,  232,
      231,  228,  227,  226,  225,  224,  223,  222,  221,  220,
      217,  216,  215,  214,  213,  212,  211,  210,  209,  208,
      207,  206,  198,  195,  194,  186,  185,  184,  181,  180,
      179,  176,  175,  174,  173,  172,  169,  168,  167,  166,
      165,  164,  163,  162,  161,  160,  159,  158,  157,  156,
      153,  152,  151,  150,  149,  148,  147,  146,  141,  137,
      131,  130,  129,  128,  127,  119,  112,  108,   87,   84,
       71,   70,   68,  386,    9,  386,  386,  386,  386,  386,

      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386
    } ;

static const flex_int16_t yy_chk[554] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
        4,    4,    5,    5,   23,    5,  127,    3,  127,    4,
        6,    6,   23,    6,    7,    7,    8,    8,   24,   24,
       25,   26,   29,   29,  390,   25,  383,    5,   27,   26,
       27,   27,   31,   31,   33,    6,   27,   37,   38,   33,

       38,   26,   24,   27,   39,  382,   40,   38,   27,   95,
       95,   39,   37,   42,   39,   40,   41,   39,   41,   47,
       46,   42,   44,   42,   46,   50,   42,   41,   44,   44,
       49,   81,   81,   50,   47,  111,  111,   47,   46,  169,
       49,   49,  169,   49,   81,   49,   64,   64,  381,   64,
       74,   74,   78,   78,  117,   79,   74,   79,   78,  117,
       79,   79,  121,   74,   80,  380,   80,   80,   74,  125,
       78,   64,   80,  126,  144,  144,  125,  121,  379,   80,
       64,  158,  158,  378,   80,  140,  140,   64,  138,  138,
       64,  126,   64,  376,  138,  126,  375,  139,  140,  139,

      374,  138,  139,  139,  142,  142,  138,  143,  373,  143,
      142,  372,  143,  143,  145,  145,  371,  142,  196,  196,
      197,  197,  142,  199,  199,  368,  200,  145,  200,  199,
      367,  200,  200,  197,  201,  201,  199,  202,  202,  203,
      203,  199,  204,  204,  205,  205,  365,  201,  254,  254,
      255,  255,  203,  257,  257,  204,  362,  205,  258,  258,
      361,  254,  360,  255,  259,  259,  260,  260,  298,  298,
      359,  258,  299,  299,  357,  356,  354,  259,  353,  260,
      352,  298,  351,  348,  347,  299,  387,  387,  387,  388,
      388,  388,  389,  389,  389,  391,  346,  391,  392,  392,

      392,  345,  344,  343,  342,  339,  338,  337,  333,  331,
      330,  329,  327,  326,  324,  322,  318,  317,  316,  314,
      313,  311,  310,  309,  307,  306,  305,  303,  302,  300,
      297,  295,  294,  293,  292,  291,  289,  288,  286,  285,
      284,  283,  282,  281,  280,  279,  278,  277,  275,  274,
      273,  272,  271,  266,  265,  264,  263,  262,  261,  256,
      253,  252,  249,  248,  246,  245,  244,  243,  242,  241,
      240,  239,  238,  237,  236,  234,  232,  231,  230,  229,
      227,  226,  225,  224,  221,  220,  219,  218,  217,  215,
      212,  211,  210,  209,  208,  207,  206,  198,  194,  193,

      192,  190,  189,  188,  187,  186,  185,  184,  183,  182,
      181,  180,  179,  178,  177,  176,  175,  173,  172,  171,
      170,  168,  166,  165,  164,  163,  162,  161,  160,  159,
      157,  156,  155,  154,  153,  152,  151,  150,  149,  148,
      147,  146,  141,  135,  128,  124,  123,  122,  120,  119,
      118,  116,  115,  114,  113,  112,  110,  108,  107,  106,
      105,  104,  103,  102,  101,  100,   99,   98,   97,   96,
       94,   93,   92,   91,   90,   89,   88,   87,   75,   67,
       59,   58,   54,   52,   51,   48,   45,   43,   32,   30,
       21,   17,   13,    9,  386,  386,  386,  386,  386,  386,

      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "meta1_lexer.l"
#line 2 "meta1_lexer.l"
    /* place here any C variables and definitions */

    #include <string.h>
    #include <stdlib.h>
    #include <stdio.h>

    int line = 1;
    int column = 1;

    char* string_buffer = NULL;
    int string_buffer_size = 0;
    int string_buffer_index = 0;
    
    /* Track if we've seen invalid escapes in current string */
    int string_has_invalid_escape = 0;
    int string_start_line = 0;
    int string_start_column = 0;
    
    /* Track comment start position for error messages */
    int comment_start_line = 0;
    int comment_start_column = 0;

    #define STRING_BUFFER_INITIAL_SIZE 64
    #define STRING_BUFFER_GROWTH_FACTOR 2
    #define YY_USER_ACTION column += yyleng;

    void ensure_string_buffer_capacity(int needed_size){
        if(string_buffer_index + needed_size >= string_buffer_size){
            int new_buffer_size = string_buffer_size * STRING_BUFFER_GROWTH_FACTOR + needed_size;

            if(new_buffer_size < STRING_BUFFER_INITIAL_SIZE) new_buffer_size = STRING_BUFFER_INITIAL_SIZE;

            string_buffer = realloc(string_buffer, new_buffer_size);

            if(!string_buffer){
                fprintf(stderr, "Fatal error: out of memory\n");
                exit(1);
            }

            string_buffer_size = new_buffer_size;
        }
    }

    void init_string_buffer(){
        if(!string_buffer){
            string_buffer_size = STRING_BUFFER_INITIAL_SIZE;
            string_buffer = malloc(string_buffer_size);

            if(!string_buffer){
                fprintf(stderr, "Fatal error: out of memory\n");
                exit(1);
            }
        }
        string_buffer_index = 0;
        string_buffer[0] = '\0';
        string_has_invalid_escape = 0;
    }

    void free_string_buffer(){
        free(string_buffer);
        string_buffer = NULL;
        string_buffer_index = 0;
        string_buffer_size = 0;
        string_has_invalid_escape = 0;
    }

    /* Helper function to print string with escape sequences */
    void print_escaped_string(char *str) {
        printf("STRLIT(\"");
        for (int i = 0; str[i] != '\0'; i++) {
            switch (str[i]) {
                case '\n': printf("\\n"); break;
                case '\t': printf("\\t"); break;
                case '\r': printf("\\r"); break;
                case '\f': printf("\\f"); break;
                case '\\': printf("\\\\"); break;
                case '"': printf("\\\""); break;
                default: printf("%c", str[i]); break;
            }
        }
        printf("\")\n");
    }

#line 777 "lex.yy.c"
/* NATURAL: 0 or sequence starting with non-zero digit, can have underscores, ends with digit */
/* Number parts */
/* Only these five are RESERVED */
/* it needs to be down here, otherwise, some of the reserved words or even other ones might get mistaken as an identifier due to precendence in rule position */

#line 783 "lex.yy.c"

#define INITIAL 0
#define MLINE_COMMENT 1
#define STRLIT 2
#define SLINE_COMMENT 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 193 "meta1_lexer.l"


#line 196 "meta1_lexer.l"
    /* yytext is a pointer to a string */

    /* RESERVED tokens - these must come first */
#line 1010 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 387 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 495 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 199 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 200 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 201 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 202 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 203 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 204 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 205 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 206 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 207 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 208 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 209 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 210 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 211 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 212 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 213 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 214 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 215 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 216 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 217 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 218 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 219 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 220 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 221 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 222 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 223 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 224 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 225 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 226 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 227 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 228 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 229 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 230 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 231 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 232 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 233 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 234 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 235 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 236 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 237 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 238 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 239 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 240 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 241 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 242 "meta1_lexer.l"
{ printf("RESERVED(%s)\n", yytext); }
	YY_BREAK
/* Multi-character operators */
case 45:
YY_RULE_SETUP
#line 245 "meta1_lexer.l"
{ printf("AND\n"); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 246 "meta1_lexer.l"
{ printf("OR\n"); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 247 "meta1_lexer.l"
{ printf("EQ\n"); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 248 "meta1_lexer.l"
{ printf("NE\n"); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 249 "meta1_lexer.l"
{ printf("GE\n"); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 250 "meta1_lexer.l"
{ printf("LE\n"); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 251 "meta1_lexer.l"
{ printf("ARROW\n"); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 252 "meta1_lexer.l"
{ printf("LSHIFT\n"); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 253 "meta1_lexer.l"
{ printf("RSHIFT\n"); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 254 "meta1_lexer.l"
{ printf("XOR\n"); }
	YY_BREAK
/* Single-character operators - STAR absolutely first */
case 55:
YY_RULE_SETUP
#line 257 "meta1_lexer.l"
{ printf("STAR\n"); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 258 "meta1_lexer.l"
{ printf("DIV\n"); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 259 "meta1_lexer.l"
{ printf("MOD\n"); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 260 "meta1_lexer.l"
{ printf("PLUS\n"); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 261 "meta1_lexer.l"
{ printf("MINUS\n"); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 262 "meta1_lexer.l"
{ printf("ASSIGN\n"); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 263 "meta1_lexer.l"
{ printf("COMMA\n"); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 264 "meta1_lexer.l"
{ printf("LT\n"); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 265 "meta1_lexer.l"
{ printf("GT\n"); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 266 "meta1_lexer.l"
{ printf("NOT\n"); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 267 "meta1_lexer.l"
{ printf("LPAR\n"); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 268 "meta1_lexer.l"
{ printf("RPAR\n"); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 269 "meta1_lexer.l"
{ printf("LBRACE\n"); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 270 "meta1_lexer.l"
{ printf("RBRACE\n"); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 271 "meta1_lexer.l"
{ printf("LSQ\n"); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 272 "meta1_lexer.l"
{ printf("RSQ\n"); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 273 "meta1_lexer.l"
{ printf("SEMICOLON\n"); }
	YY_BREAK
/* Keywords */
case 72:
YY_RULE_SETUP
#line 276 "meta1_lexer.l"
{ printf("BOOLLIT(%s)\n",yytext); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 277 "meta1_lexer.l"
{ printf("BOOL\n"); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 278 "meta1_lexer.l"
{ printf("CLASS\n"); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 279 "meta1_lexer.l"
{ printf("DOTLENGTH\n"); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 280 "meta1_lexer.l"
{ printf("DOUBLE\n"); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 281 "meta1_lexer.l"
{ printf("ELSE\n"); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 282 "meta1_lexer.l"
{ printf("IF\n"); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 283 "meta1_lexer.l"
{ printf("INT\n"); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 284 "meta1_lexer.l"
{ printf("PRINT\n"); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 285 "meta1_lexer.l"
{ printf("PARSEINT\n"); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 286 "meta1_lexer.l"
{ printf("PUBLIC\n"); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 287 "meta1_lexer.l"
{ printf("RETURN\n"); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 288 "meta1_lexer.l"
{ printf("STATIC\n"); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 289 "meta1_lexer.l"
{ printf("STRING\n"); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 290 "meta1_lexer.l"
{ printf("VOID\n"); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 291 "meta1_lexer.l"
{ printf("WHILE\n"); }
	YY_BREAK
/* Comment patterns */
case 88:
YY_RULE_SETUP
#line 294 "meta1_lexer.l"
{ 
    BEGIN(MLINE_COMMENT); 
    comment_start_line = line;
    comment_start_column = column - yyleng;
}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 299 "meta1_lexer.l"
{ BEGIN(SLINE_COMMENT); }
	YY_BREAK
/* treating general stuff */
/* DECIMAL patterns - must come BEFORE natural */
/* Format: integer part . fractional part exponent? */
case 90:
YY_RULE_SETUP
#line 305 "meta1_lexer.l"
{ printf("DECIMAL(%s)\n",yytext); }
	YY_BREAK
/* Format: integer part . exponent? (with optional fractional) */
case 91:
YY_RULE_SETUP
#line 307 "meta1_lexer.l"
{ printf("DECIMAL(%s)\n",yytext); }
	YY_BREAK
/* Format: . fractional part exponent? */
case 92:
YY_RULE_SETUP
#line 309 "meta1_lexer.l"
{ printf("DECIMAL(%s)\n",yytext); }
	YY_BREAK
/* Format: integer part exponent (no dot) */
case 93:
YY_RULE_SETUP
#line 311 "meta1_lexer.l"
{ printf("DECIMAL(%s)\n",yytext); }
	YY_BREAK
/* Then NATURAL */
case 94:
YY_RULE_SETUP
#line 314 "meta1_lexer.l"
{ printf("NATURAL(%s)\n",yytext); }
	YY_BREAK
/* Then IDENTIFIER */
case 95:
YY_RULE_SETUP
#line 317 "meta1_lexer.l"
{ printf("IDENTIFIER(%s)\n",yytext); }
	YY_BREAK
case 96:
/* rule 96 can match eol */
YY_RULE_SETUP
#line 320 "meta1_lexer.l"
{ 
    if (yytext[0] == '\n') { 
        line++; 
        column = 1;
    } else if (yytext[0] == '\r') {
        /* Handle carriage return */
        column = 1;
    } else if (yytext[0] == '\t') {
        column += 8 - ((column - 1) % 8);
    }
    /* Ignore other whitespace */
}
	YY_BREAK
/* treating strings */
case 97:
YY_RULE_SETUP
#line 336 "meta1_lexer.l"
{ 
    BEGIN(STRLIT); 
    init_string_buffer(); 
    string_start_line = line;
    string_start_column = column - yyleng;
}
	YY_BREAK
/* Valid escape sequences */
case 98:
YY_RULE_SETUP
#line 344 "meta1_lexer.l"
{
    ensure_string_buffer_capacity(1);
    switch(yytext[1]) 
    {
        case 'n' : string_buffer[string_buffer_index++] = '\n'; break;
        case 't' : string_buffer[string_buffer_index++] = '\t'; break;
        case 'r' : string_buffer[string_buffer_index++] = '\r'; break;
        case 'f' : string_buffer[string_buffer_index++] = '\f'; break;
        case '\\': string_buffer[string_buffer_index++] = '\\'; break;
        case '"' : string_buffer[string_buffer_index++] = '"'; break;
    }
}
	YY_BREAK
/* Backslash at end of line - line continuation */
case 99:
/* rule 99 can match eol */
YY_RULE_SETUP
#line 358 "meta1_lexer.l"
{
    line++;
    column = 1;
    /* Don't add anything to buffer */
}
	YY_BREAK
case 100:
/* rule 100 can match eol */
YY_RULE_SETUP
#line 364 "meta1_lexer.l"
{
    line++;
    column = 1;
    /* Don't add anything to buffer */
}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 370 "meta1_lexer.l"
{
    line++;
    column = 1;
    /* Don't add anything to buffer */
}
	YY_BREAK
/* Invalid escape sequences - any other backslash combination */
case 102:
YY_RULE_SETUP
#line 377 "meta1_lexer.l"
{ 
    printf("Line %d, col %d: invalid escape sequence (%s)\n",
           line, column - yyleng, yytext);
    string_has_invalid_escape = 1;
}
	YY_BREAK
/* Unterminated string - newline without backslash */
case 103:
/* rule 103 can match eol */
YY_RULE_SETUP
#line 384 "meta1_lexer.l"
{
    printf("Line %d, col %d: unterminated string literal\n", 
           string_start_line, string_start_column);
    
    free_string_buffer();
    BEGIN(INITIAL);
    /* Let whitespace rule handle the newline */
}
	YY_BREAK
/* Normal string characters */
case 104:
YY_RULE_SETUP
#line 394 "meta1_lexer.l"
{
    ensure_string_buffer_capacity(yyleng);
    memcpy(string_buffer + string_buffer_index, yytext, yyleng);
    string_buffer_index += yyleng; 
}
	YY_BREAK
/* End of string */
case 105:
YY_RULE_SETUP
#line 401 "meta1_lexer.l"
{ 
    if (string_has_invalid_escape) {
        /* String had invalid escapes - discard it */
        free_string_buffer();
        BEGIN(INITIAL);
    } else {
        /* Valid string - print it */
        ensure_string_buffer_capacity(1);
        string_buffer[string_buffer_index] = '\0';
        print_escaped_string(string_buffer);
        free_string_buffer();
        BEGIN(INITIAL);
    }
}
	YY_BREAK
/* EOF in string */
case YY_STATE_EOF(STRLIT):
#line 417 "meta1_lexer.l"
{
    printf("Line %d, col %d: unterminated string literal\n", 
           string_start_line, string_start_column);
    free_string_buffer();
    BEGIN(INITIAL);
    yyterminate();
}
	YY_BREAK
/* treating comments - continuation */
case 106:
YY_RULE_SETUP
#line 428 "meta1_lexer.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 107:
/* rule 107 can match eol */
YY_RULE_SETUP
#line 430 "meta1_lexer.l"
{ 
    /* Handle all types of line endings */
    if (yytext[yyleng-1] == '\n' || yytext[0] == '\r') line++; 
    column = 1; 
}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 436 "meta1_lexer.l"
{ /* ignore */ }
	YY_BREAK
case YY_STATE_EOF(MLINE_COMMENT):
#line 438 "meta1_lexer.l"
{ 
    printf("Line %d, col %d: unterminated comment\n", 
           comment_start_line, comment_start_column);
    BEGIN(INITIAL);
    yyterminate();
}
	YY_BREAK
case 109:
/* rule 109 can match eol */
YY_RULE_SETUP
#line 445 "meta1_lexer.l"
{ 
    if (yytext[yyleng-1] == '\n' || yytext[0] == '\r') line++; 
    column = 1; 
    BEGIN(INITIAL); 
}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 451 "meta1_lexer.l"
{ /* ignore */ }
	YY_BREAK
case YY_STATE_EOF(SLINE_COMMENT):
#line 453 "meta1_lexer.l"
{ BEGIN(INITIAL); }
	YY_BREAK
/* illegal characters - everything else */
case 111:
YY_RULE_SETUP
#line 458 "meta1_lexer.l"
{ 
    printf("Line %d, col %d: illegal character (%s)\n", 
           line, column - yyleng, yytext); 
}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 463 "meta1_lexer.l"
ECHO;
	YY_BREAK
#line 1760 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 387 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 387 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 386);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 463 "meta1_lexer.l"


extern int yylex();
int main() {
    yylex();
    free_string_buffer();
    return 0;
}

int yywrap() {
    return 1;
}
